title: Dormilabo - Your freelance partner
email: dormilabo@gmail.com
description: a freelance project aim to provide outsource MIS solutions and services to the SMEs and Entrepreneurs - IT Equipment - Website and Software development - Customized training - Content authoring
baseurl: /
url: https://dormilabo.github.io
twitter_username: dormilabo
github_username: dormilabo

# Build settings
theme: minima
plugins:
  - jekyll-feed
